### ISSUE TITLE
Support Firefox Mobile

### ISSUE THREAD

**Issue by PanderMusubi** [cadeyrn/keep-or-delete-bookmarks#4] opened 2019-07-15 11:55 UTC
Please, support also Firefox Mobile so that this add-on can be used on smartphone and tablets.

**Comment by cadeyrn** [comment] 2019-07-15 12:02
That's not possible, at least not at the moment. Firefox 68 for Android has no bookmarks API for WebExtensions and "the old Firefox" won't get any new features, Firefox 68 was the last feature update. Mozilla is working on new Android browser (aka "Fenix" or "Firefox Preview") which has no WebExtension support at all (yet). It's possible that the new Android browser will get WebExtension support in the future but it's not yet confirmed and I don't know if there will be a bookmarks API for WebExtensions in the future.

On Firefox for iOS there is no WebExtension support at all.

I'll close this issue because it's not actionable at the moment but if / once there will be a WebExtension bookmark API for mobile in the future I will support this.

**Closed as completed by cadeyrn** 2019-07-15 12:02 UTC
Labels: WebExtension restriction

**Comment by PanderMusubi** [comment] 2019-07-15 12:05
Fair to close it. Perhaps an alternate way is to use the API of Firefox Sync to access and manage the bookmarks. Thanks for explaination.
